<<<<<<< HEAD
import Header from "@/components/header";
import Wrapper from "@/components/wrapper";
import { Children } from "react";

export default function StoreLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <Header />
      {children}
    </main>
  );
}
=======
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
<<<<<<<< HEAD:src/app/layout.tsx
import ClientWrapper from "./client-wrapper";
import { GeistMono } from "geist/font/mono";
========
import { SessionProvider } from "next-auth/react";
import RegisterModal from "@/components/ui/register-modal";
import SignInModal from "@/components/ui/sign-in-modal";
import { Toaster } from "react-hot-toast";
import ClientWrapper from "../client-wrapper";
import QueryProvider from "@/lib/query-provider";
const poppins = Poppins({ subsets: ["latin"], weight: "400" });
>>>>>>>> 8d80a130897fc9effc781d0d54fe31fcf3c1f3fe:src/app/(store)/layout.tsx

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<<< HEAD:src/app/layout.tsx
      <body className={GeistMono.className}>
========
      <body className={poppins.className}>
>>>>>>>> 8d80a130897fc9effc781d0d54fe31fcf3c1f3fe:src/app/(store)/layout.tsx
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
>>>>>>> 8d80a130897fc9effc781d0d54fe31fcf3c1f3fe
