import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import ClientWrapper from "./client-wrapper";
import { GeistMono } from "geist/font/mono";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistMono.className}>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
